### ISSUE TITLE
fail to run with error 'GLIBC_2.25' not found

### ISSUE THREAD

**Issue by zhangpy** [RadhiFadlillah/qamel#14]
I use hello world demo and build with 
```
qamel docker linux-static
```
Build finished successfully. 
but when I run, I got error
```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found
```
My platform is ubuntu16.04

It is better if could build everything with static link.

**Comment by RadhiFadlillah** [comment]
Yeah, the static build for Linux is a bit spotty. There is also issue with number pad not working on static Linux build. I will look at it as soon as possible.

**Comment by RadhiFadlillah** [comment]
@zhangpy could you try it again ? 

Make sure to update `qamel` and Docker image for `linux-static` first :

```
go get -u -v github.com/RadhiFadlillah/qamel/cmd/qamel
docker pull radhifadlillah/qamel:linux-static
```

I've reverted the Docker image to use Ubuntu 16.04 as base instead of Ubuntu 18.04, which hopefuly fixed this issue. Along with it, I also fixed issues where numpad not working and fontconfig warning show up when app is started.

**Comment by zhangpy** [comment]
Thanks for the response. I am sorry I missed the mail and just find it right now. 
I have a try but build failed with error message:
```
$>qamel docker linux-static
Run `qamel build` from Docker image.
Starting build process.

Load config file...done
Removing old build files...done
Generating binding files...done
Generating Qt resource file...resource directory doesn't exist
Generating code for QML objects...
Failed: /home/user/go/src/src/github.com/davidrjenni/reftools/cmd/fillswitch/test-fixtures/typeswitch_5/internal/foo/foo.go:15:26: expected type, found '{'
Failed to build app using Docker: exit status 1
```

docker image ls
``
radhifadlillah/qamel   linux-static        a8743948b5de
``

**Comment by RadhiFadlillah** [comment]
Hi @zhangpy, sorry for late response as well. The job been busy, so I can only answer it today.

> `Failed: /home/user/go/src/src/github.com/davidrjenni/reftools/cmd/fillswitch/test-fixtures/typeswitch_5/internal/foo/foo.go:15:26: expected type, found '{'`

I'm sorry, but I don't think it's `qamel` fault, because :

- Qamel doesn't use `github.com/davidrjenni/reftools` as its [dependency](https://github.com/RadhiFadlillah/qamel/blob/master/go.mod);
- The error message indicates that there is some code with wrong syntax, which makes the `qamel build` failed. Therefore, it shows that `qamel build` works as intended.

My guess is you run `qamel build` inside `$GOPATH/src` instead of inside your project. You should open the terminal inside your project dir (for example `/home/zhangpy/hello-world`) then run `qamel build` there :

```
cd /home/zhangpy/hello-world
qamel build
```

**Comment by zhangpy** [comment]
Yes, I build it today inside/outside gopath and both compile successfully. :)
I don't know how to explain this. thanks for your detailed response.

**Comment by RadhiFadlillah** [comment]
Yep, glad I could help :smile:
