### ISSUE TITLE
qamel docker win64 --copy-deps blocked

### ISSUE THREAD

**Issue by fcying** [RadhiFadlillah/qamel#4]
```
~/go/src/github.com/RadhiFadlillah/qamel/example/hello-world ‹master›$ qamel docker win64 --copy-deps                                                                           
Run `qamel build` from Docker image.
Starting build process.

Load config file...done
Removing old build files...done
Generating binding files...done
Generating Qt resource file...done
Generating syso file...icon file doesn't exist
Generating code for QML objects...done
Building app...done
Copying dependencies...
```

I waited for half an hour, the size has not increased
```
~/go/src/github.com/RadhiFadlillah/qamel/example/hello-world ‹master›$ du -sh .
3.3M    .

```

The generated exe file can work in windows.

**Comment by RadhiFadlillah** [comment]
HI @fcying, can I know what is your operating system and architecture ?

**Comment by fcying** [comment]
```
Linux lin 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

Docker version 18.09.0, build 4d60db4

go version go1.11.2 linux/amd64
```

**Comment by RadhiFadlillah** [comment]
@fcying it should be fixed by [c05136](https://github.com/RadhiFadlillah/qamel/commit/c0513680a934ef44e71c0a1e48731d8c7109f5e1). The problem is happened because there was [uncaught](https://github.com/RadhiFadlillah/qamel/blob/5e90ca5daa75cec68929199f5ece1d9e5a3cc38c/qamel/generator/gen-deps-windows.go#L103) error which makes the loop never end.

To fix it, first upgrade the qamel binding :

```
go get -u -v github.com/RadhiFadlillah/qamel/qamel
go get -u -d -v github.com/RadhiFadlillah/qamel
```

Then pull the new Docker images :

```
docker pull radhifadlillah/qamel:win64
```

Now you should be able to build like usual :

```
cd $(go env GOPATH)/src/github.com/RadhiFadlillah/qamel/example/hello-world
qamel docker win64 --copy-deps
```

Hopefully it works now, but feels free to report if it hasn't fixed.

P.S. by the way, image for `win32` and `linux` also changed, so if you use it, pull them as well.

**Comment by fcying** [comment]
It can work now, tks~

P.S. all deps files copy to the source folder, it looks a bit messy. May be use a `build` folder?

**Comment by RadhiFadlillah** [comment]
@fcying I was planning to create a specific build output, e.g. `qamel-build`. However, at the end I think it's better for user to specify the output target on his own. To do that, you can use `-o` flag like this :

```
qamel docker win64 -o qamel-build/hello.exe --copy-deps
```

Using command above, all dependencies will be put inside `qamel-build` directory.

**Comment by fcying** [comment]
@RadhiFadlillah Is there any way to speed up `qamel docker`? 
`qamel build`  speed is almost the same at the first build, but it will be faster to build again.
Save the docker cache to the local, use a `qamel docker` options to use it?

**Comment by RadhiFadlillah** [comment]
@fcying sure, I will investigate it later.

For now, would you create new issue for it ? This way it's easier to track.
