### ISSUE TITLE
[feature request] qamel docker support cache for speed up build

### ISSUE THREAD

**Issue by fcying** [RadhiFadlillah/qamel#6]
add docker args  `-v ./qamel_cache:/home/user/.cache/go-build` let `qamel docker` can use last build cache.
it may be speed up build time.

It may be a option, default `qamel docker` is not use cache,  `qamel docker --cache` use cache.

**Comment by RadhiFadlillah** [comment]
I've added this on [1a1c839](https://github.com/RadhiFadlillah/qamel/commit/1a1c839068defd351962969374f4ef00b6076083).

> It may be a option, default `qamel docker` is not use cache, `qamel docker --cache` use cache.

I decided to make `qamel docker` always uses cache because as it is right now Go command will periodically deletes cached data that has not been used recently, so it's fine to keep saving the cache.

**Comment by fcying** [comment]
awesome~_~ `qamel docker` has speeded up.
```
~/go/src/github.com/RadhiFadlillah/qamel/example/hello-world ‹master›$ rm -rf .qamel-cache
~/go/src/github.com/RadhiFadlillah/qamel/example/hello-world ‹master›$ time qamel docker win64 -o build/hello.exe
qamel docker win64 -o build/hello.exe  0.03s user 0.04s system 0% cpu 7.511 total

~/go/src/github.com/RadhiFadlillah/qamel/example/hello-world ‹master›$ time qamel docker win64 -o build/hello.exe
qamel docker win64 -o build/hello.exe  0.02s user 0.04s system 5% cpu 1.137 total
```
