### ISSUE TITLE
[feature request] support QQuickStyle

### ISSUE THREAD

**Issue by fcying** [RadhiFadlillah/qamel#9]
It's a easy way to support qml style

C++ version:
```
QT += quickcontrols2

#include <QQuickStyle>
QQuickStyle::setStyle("Fusion");
```

**Comment by RadhiFadlillah** [comment]
Hi @fcying, thanks for the PR :+1:

I've merged your PR, but I've made one little [change](https://github.com/RadhiFadlillah/qamel/commit/8cbf10908935bb06bf54cd8750c96a2fb47ed19d) by renaming `SetQuickFallbackStyle` into `SetQuickStyleFallback`.

This is done because `SetQuickFallbackStyle` can be translated as "set style for `QuickFallback`", which is not we want. What we want is to set the fallback for the `QuickStyle`, hence why I rename it into `SetQuickStyleFallback`.
